module.exports = {
  apps: [
    {
      name: 'gaqno-shell',
      cwd: './gaqno-shell',
      script: 'npm',
      args: 'run dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      error_file: './logs/shell-error.log',
      out_file: './logs/shell-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-sso',
      cwd: './gaqno-sso',
      script: 'npm',
      args: 'run dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3001,
      },
      error_file: './logs/sso-error.log',
      out_file: './logs/sso-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-ai',
      cwd: './gaqno-ai',
      script: 'npm',
      args: 'run dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3002,
      },
      error_file: './logs/ai-error.log',
      out_file: './logs/ai-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-crm',
      cwd: './gaqno-crm',
      script: 'npm',
      args: 'run dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3003,
      },
      error_file: './logs/crm-error.log',
      out_file: './logs/crm-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-erp',
      cwd: './gaqno-erp',
      script: 'npm',
      args: 'run dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3004,
      },
      error_file: './logs/erp-error.log',
      out_file: './logs/erp-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-finance',
      cwd: './gaqno-finance',
      script: 'npm',
      args: 'run dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3005,
      },
      error_file: './logs/finance-error.log',
      out_file: './logs/finance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-pdv',
      cwd: './gaqno-pdv',
      script: 'npm',
      args: 'run dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3006,
      },
      error_file: './logs/pdv-error.log',
      out_file: './logs/pdv-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-rpg',
      cwd: './gaqno-rpg',
      script: 'npm',
      args: 'run dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3007,
      },
      error_file: './logs/rpg-error.log',
      out_file: './logs/rpg-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-sso-service',
      cwd: './gaqno-sso-service',
      script: 'npm',
      args: 'run start:dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 4001,
      },
      error_file: './logs/sso-service-error.log',
      out_file: './logs/sso-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-ai-service',
      cwd: './gaqno-ai-service',
      script: 'npm',
      args: 'run start:dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 4002,
      },
      error_file: './logs/ai-service-error.log',
      out_file: './logs/ai-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-finance-service',
      cwd: './gaqno-finance-service',
      script: 'npm',
      args: 'run start:dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 4005,
      },
      error_file: './logs/finance-service-error.log',
      out_file: './logs/finance-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-pdv-service',
      cwd: './gaqno-pdv-service',
      script: 'npm',
      args: 'run start:dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 4006,
      },
      error_file: './logs/pdv-service-error.log',
      out_file: './logs/pdv-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gaqno-rpg-service',
      cwd: './gaqno-rpg-service',
      script: 'npm',
      args: 'run start:dev',
      watch: false,
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 4007,
      },
      error_file: './logs/rpg-service-error.log',
      out_file: './logs/rpg-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
